## These functions provide a way of caching inverse matrixes

## That function receives a matrix object as an argument and returns
## a list of getter and setter methods for both the matrix 
## and its inverse.

makeCacheMatrix <- function(x = matrix()) {
        inverse <- NULL
        
        set <- function(y) {
                x <<- y
                inverse <<- NULL
        }
        
        get <- function() x
        
        set_inverse <- function(inv) inverse <<- inv
        get_inverse <- function() inverse
        
        list(set = set, get = get,
             set_inverse = set_inverse,
             get_inverse = get_inverse)
}


## That function receives an object (generated by makeCacheMatrix),
## checks if the inverse of that matrix (defined inside that object)
## already has been defined (in which case the inverse is returned) 
## or calculates the inverse and caches it inside the object.

cacheSolve <- function(x, ...) {
        inverse <- x$get_inverse()

        if(!is.null(inverse)) {
                message("getting cached data")
                return(inverse)
        }

        matrix <- x$get()
        inverse <- solve(matrix)
        x$set_inverse(inverse)
        inverse
}


cm <- makeCacheMatrix(matrix(1:4, 2, 2))

class(cm)

print(cacheSolve(cm))

print(cacheSolve(cm))

